LambdaForums/Controllers/ForumController.cs
using LambdaForums.Data;
using LambdaForums.Data.Models;
using LambdaForums.Models.ForumViewModels;
using LambdaForums.Models.PostViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace LambdaForums.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;

        public ForumController(IForum forumService)
        {
            _forumService = forumService;
        }

        public IActionResult Index()
        {
            var forums = _forumService.GetAll().Select(x => new ForumListingModel
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description
            });

            var indexModel = new ForumIndexModel
            {
                ForumList = forums
            };

            return View(indexModel);
        }

        public IActionResult Topic(int id)
        {
            var forum = _forumService.GetById(id);
            var posts = forum.Posts;

            var postListings = posts.Select(x => new PostListingModel
            {
                Id = x.Id,
                AuthorId = x.User.Id,
                AuthorRating = x.User.Rating,
                Title = x.Title,
                DatePosted = x.Created.ToString(),
                RepliesCount = x.Replies.Count(),
                Forum = BuildForumListing(x)
            });

            var model = new ForumTopicViewModel
            {
                Posts = postListings,
                Forum = BuildForumListing(forum)
            };

            return View(model);
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;

            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Title = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }
    }
}

LambdaForums/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using LambdaForums.Data;
using LambdaForums.Data.Models;
using LambdaForums.Models.PostViewModels;
using LambdaForums.Models.ReplyViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LambdaForums.Controllers
{
    public class PostController : Controller
    {
        private readonly IPost _postService;

        public PostController(IPost postService)
        {
            _postService = postService;
        }

        public IActionResult Index(int id)
        {
            var post = _postService.GetById(id);

            var replies = BuildPostReplies(post.Replies);

            var model = new PostIndexViewModel
            {
                Id = post.Id,
                Title = post.Title,
                AuthorId = post.User.Id,
                AuthorName = post.User.UserName,
                AuthorImageUrl = post.User.ProfileImageUrl,
                AuthorRating = post.User.Rating,
                Created = post.Created,
                PostContent = post.Content,
                Replies = replies
            };

            return View(model);
        }

        private IEnumerable<PostReplyModel> BuildPostReplies(IEnumerable<PostReply> replies)
        {
            return replies.Select(x => new PostReplyModel
            {
                Id = x.Id,
                AuthorName = x.User.UserName,
                AuthorId = x.User.Id,
                AuthorImageUrl = x.User.ProfileImageUrl,
                AuthorRating = x.User.Rating,
                Created = x.Created,
                ReplyContent = x.Content
            });
        }
    }
}

LambdaForums/Views/Forum/Index.cshtml
@model LambdaForums.Models.ForumViewModels.ForumIndexModel

<h1>Forums</h1>

<table class="table table-hover" id="forumIndexTable">
    <tbody>
        @foreach (var forum in Model.ForumList)
        {
        <tr>
            <td>
                <a asp-controller="Forum" asp-action="Topic" asp-route-id="@forum.Id">
                    @forum.Title
                </a>                
            </td>
            <td>
                @forum.Description
            </td>
        </tr>
        }
    </tbody>
</table>

LambdaForums/Views/Forum/Topic.cshtml
@model LambdaForums.Models.ForumViewModels.ForumTopicViewModel

<h1>Welcome to the @Model.Forum.Title Forum!</h1>

@if (Model.Posts.Any())
{
    <table class="table table-bordered table-hover">
        <tbody>
            @foreach (var post in Model.Posts)
            {
                <tr>
                    <td>
                        <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">@post.Title</a>
                    </td>
                    <td>@post.AuthorName</td>
                    <td>@post.DatePosted</td>
                    <td>@post.RepliesCount</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="noPosts">
        <h3>
            It looks like there are no @Model.Forum.Title posts yet. <br />
            Why not
            <a asp-controller="Post" asp-action="Create" asp-route-id="@Model.Forum.Id">
                <span>create</span>
            </a>
            one?
        </h3>
    </div>
}